name: primal
description: A declarative, functional, open source programming language focused on simplicity and minimalism.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.5.1 <4.0.0'

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^4.0.0
