name: primal
description: A declarative, functional, open source programming language focused on simplicity and minimalism.
publish_to: none
version: 0.4.2

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  path: ^1.9.1
  crypto: ^3.0.7
  characters: ^1.4.1

dev_dependencies:
  test: ^1.31.0
  flutter_lints: ^6.0.0
