name: primal
description: A declarative, functional, open source programming language focused on simplicity and minimalism.
publish_to: none
version: 0.3.0

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  path: ^1.9.0
  crypto: ^3.0.5

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^4.0.0
